// Mocks generated by Mockito 5.4.4 from annotations
// in trackflow/test/features/audio_track/domain/usecases/delete_audio_track_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i14;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trackflow/core/app_flow/data/session_storage.dart' as _i4;
import 'package:trackflow/core/entities/unique_id.dart' as _i9;
import 'package:trackflow/core/error/failures.dart' as _i7;
import 'package:trackflow/core/infrastructure/domain/directory_service.dart'
    as _i20;
import 'package:trackflow/features/audio_cache/domain/entities/cached_audio.dart'
    as _i19;
import 'package:trackflow/features/audio_cache/domain/failures/cache_failure.dart'
    as _i18;
import 'package:trackflow/features/audio_cache/domain/repositories/audio_storage_repository.dart'
    as _i17;
import 'package:trackflow/features/audio_comment/domain/entities/audio_comment.dart'
    as _i22;
import 'package:trackflow/features/audio_comment/domain/repositories/audio_comment_repository.dart'
    as _i21;
import 'package:trackflow/features/audio_track/domain/entities/audio_track.dart'
    as _i11;
import 'package:trackflow/features/audio_track/domain/repositories/audio_track_repository.dart'
    as _i3;
import 'package:trackflow/features/audio_track/domain/services/project_track_service.dart'
    as _i10;
import 'package:trackflow/features/projects/domain/entities/project.dart'
    as _i8;
import 'package:trackflow/features/projects/domain/repositories/projects_repository.dart'
    as _i6;
import 'package:trackflow/features/track_version/domain/entities/track_version.dart'
    as _i13;
import 'package:trackflow/features/track_version/domain/repositories/track_version_repository.dart'
    as _i12;
import 'package:trackflow/features/waveform/domain/entities/audio_waveform.dart'
    as _i16;
import 'package:trackflow/features/waveform/domain/repositories/waveform_repository.dart'
    as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioTrackRepository_1 extends _i1.SmartFake
    implements _i3.AudioTrackRepository {
  _FakeAudioTrackRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SessionStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionStorage extends _i1.Mock implements _i4.SessionStorage {
  MockSessionStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #saveUserId,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> clearUserId() => (super.noSuchMethod(
        Invocation.method(
          #clearUserId,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void debugPrintAllValues() => super.noSuchMethod(
        Invocation.method(
          #debugPrintAllValues,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getString(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool?> getBool(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [key],
        ),
        returnValue: _i5.Future<bool?>.value(),
      ) as _i5.Future<bool?>);

  @override
  _i5.Future<void> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ProjectsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectsRepository extends _i1.Mock
    implements _i6.ProjectsRepository {
  MockProjectsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i8.Project>> createProject(
          _i8.Project? project) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProject,
          [project],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i8.Project>>.value(
            _FakeEither_0<_i7.Failure, _i8.Project>(
          this,
          Invocation.method(
            #createProject,
            [project],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i8.Project>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> updateProject(
          _i8.Project? project) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProject,
          [project],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #updateProject,
            [project],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> deleteProject(
          _i8.Project? project) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProject,
          [project],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteProject,
            [project],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i8.Project>> getProjectById(
          _i9.ProjectId? projectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjectById,
          [projectId],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i8.Project>>.value(
            _FakeEither_0<_i7.Failure, _i8.Project>(
          this,
          Invocation.method(
            #getProjectById,
            [projectId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i8.Project>>);

  @override
  _i5.Stream<_i2.Either<_i7.Failure, List<_i8.Project>>> watchLocalProjects(
          _i9.UserId? ownerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchLocalProjects,
          [ownerId],
        ),
        returnValue:
            _i5.Stream<_i2.Either<_i7.Failure, List<_i8.Project>>>.empty(),
      ) as _i5.Stream<_i2.Either<_i7.Failure, List<_i8.Project>>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> clearLocalCache() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearLocalCache,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #clearLocalCache,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Stream<_i2.Either<_i7.Failure, _i8.Project?>> watchProjectById(
          _i9.ProjectId? projectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchProjectById,
          [projectId],
        ),
        returnValue: _i5.Stream<_i2.Either<_i7.Failure, _i8.Project?>>.empty(),
      ) as _i5.Stream<_i2.Either<_i7.Failure, _i8.Project?>>);
}

/// A class which mocks [ProjectTrackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectTrackService extends _i1.Mock
    implements _i10.ProjectTrackService {
  MockProjectTrackService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AudioTrackRepository get trackRepository => (super.noSuchMethod(
        Invocation.getter(#trackRepository),
        returnValue: _FakeAudioTrackRepository_1(
          this,
          Invocation.getter(#trackRepository),
        ),
      ) as _i3.AudioTrackRepository);

  @override
  _i5.Stream<
      _i2.Either<_i7.Failure, List<_i11.AudioTrack>>> watchTracksByProject(
          _i9.ProjectId? projectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTracksByProject,
          [projectId],
        ),
        returnValue:
            _i5.Stream<_i2.Either<_i7.Failure, List<_i11.AudioTrack>>>.empty(),
      ) as _i5.Stream<_i2.Either<_i7.Failure, List<_i11.AudioTrack>>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i11.AudioTrack>> addTrackToProject({
    required _i8.Project? project,
    required _i9.UserId? requester,
    required String? name,
    required String? url,
    Duration? duration,
    _i9.TrackVersionId? activeVersionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTrackToProject,
          [],
          {
            #project: project,
            #requester: requester,
            #name: name,
            #url: url,
            #duration: duration,
            #activeVersionId: activeVersionId,
          },
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i11.AudioTrack>>.value(
            _FakeEither_0<_i7.Failure, _i11.AudioTrack>(
          this,
          Invocation.method(
            #addTrackToProject,
            [],
            {
              #project: project,
              #requester: requester,
              #name: name,
              #url: url,
              #duration: duration,
              #activeVersionId: activeVersionId,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i11.AudioTrack>>);

  @override
  _i2.Either<_i7.Failure, _i11.AudioTrack> createTrackEntity({
    required _i8.Project? project,
    required _i9.UserId? requester,
    required String? name,
    Duration? duration,
    _i9.TrackVersionId? activeVersionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTrackEntity,
          [],
          {
            #project: project,
            #requester: requester,
            #name: name,
            #duration: duration,
            #activeVersionId: activeVersionId,
          },
        ),
        returnValue: _FakeEither_0<_i7.Failure, _i11.AudioTrack>(
          this,
          Invocation.method(
            #createTrackEntity,
            [],
            {
              #project: project,
              #requester: requester,
              #name: name,
              #duration: duration,
              #activeVersionId: activeVersionId,
            },
          ),
        ),
      ) as _i2.Either<_i7.Failure, _i11.AudioTrack>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> deleteTrack({
    required _i8.Project? project,
    required _i9.UserId? requester,
    required _i9.AudioTrackId? trackId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTrack,
          [],
          {
            #project: project,
            #requester: requester,
            #trackId: trackId,
          },
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteTrack,
            [],
            {
              #project: project,
              #requester: requester,
              #trackId: trackId,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> editTrackName({
    required _i9.AudioTrackId? trackId,
    required _i9.ProjectId? projectId,
    required String? newName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #editTrackName,
          [],
          {
            #trackId: trackId,
            #projectId: projectId,
            #newName: newName,
          },
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #editTrackName,
            [],
            {
              #trackId: trackId,
              #projectId: projectId,
              #newName: newName,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);
}

/// A class which mocks [TrackVersionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackVersionRepository extends _i1.Mock
    implements _i12.TrackVersionRepository {
  MockTrackVersionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>> addVersion({
    required _i9.AudioTrackId? trackId,
    required _i14.File? file,
    String? label,
    Duration? duration,
    required _i9.UserId? createdBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addVersion,
          [],
          {
            #trackId: trackId,
            #file: file,
            #label: label,
            #duration: duration,
            #createdBy: createdBy,
          },
        ),
        returnValue:
            _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>>.value(
                _FakeEither_0<_i7.Failure, _i13.TrackVersion>(
          this,
          Invocation.method(
            #addVersion,
            [],
            {
              #trackId: trackId,
              #file: file,
              #label: label,
              #duration: duration,
              #createdBy: createdBy,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>> addVersionOnline({
    required _i9.AudioTrackId? trackId,
    required _i14.File? file,
    String? label,
    required Duration? duration,
    required String? createdBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addVersionOnline,
          [],
          {
            #trackId: trackId,
            #file: file,
            #label: label,
            #duration: duration,
            #createdBy: createdBy,
          },
        ),
        returnValue:
            _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>>.value(
                _FakeEither_0<_i7.Failure, _i13.TrackVersion>(
          this,
          Invocation.method(
            #addVersionOnline,
            [],
            {
              #trackId: trackId,
              #file: file,
              #label: label,
              #duration: duration,
              #createdBy: createdBy,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>>);

  @override
  _i5.Stream<_i2.Either<_i7.Failure, List<_i13.TrackVersion>>>
      watchVersionsByTrack(_i9.AudioTrackId? trackId) => (super.noSuchMethod(
            Invocation.method(
              #watchVersionsByTrack,
              [trackId],
            ),
            returnValue: _i5.Stream<
                _i2.Either<_i7.Failure, List<_i13.TrackVersion>>>.empty(),
          ) as _i5.Stream<_i2.Either<_i7.Failure, List<_i13.TrackVersion>>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, List<_i13.TrackVersion>>>
      getVersionsByTrack(_i9.AudioTrackId? trackId) => (super.noSuchMethod(
            Invocation.method(
              #getVersionsByTrack,
              [trackId],
            ),
            returnValue: _i5
                .Future<_i2.Either<_i7.Failure, List<_i13.TrackVersion>>>.value(
                _FakeEither_0<_i7.Failure, List<_i13.TrackVersion>>(
              this,
              Invocation.method(
                #getVersionsByTrack,
                [trackId],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i7.Failure, List<_i13.TrackVersion>>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>> getById(
          _i9.TrackVersionId? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>>.value(
                _FakeEither_0<_i7.Failure, _i13.TrackVersion>(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>> getActiveVersion(
          _i9.AudioTrackId? trackId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveVersion,
          [trackId],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>>.value(
                _FakeEither_0<_i7.Failure, _i13.TrackVersion>(
          this,
          Invocation.method(
            #getActiveVersion,
            [trackId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i13.TrackVersion>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> setActiveVersion({
    required _i9.AudioTrackId? trackId,
    required _i9.TrackVersionId? versionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setActiveVersion,
          [],
          {
            #trackId: trackId,
            #versionId: versionId,
          },
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #setActiveVersion,
            [],
            {
              #trackId: trackId,
              #versionId: versionId,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> deleteVersion(
          _i9.TrackVersionId? versionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVersion,
          [versionId],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteVersion,
            [versionId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> renameVersion({
    required _i9.TrackVersionId? versionId,
    required String? newLabel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameVersion,
          [],
          {
            #versionId: versionId,
            #newLabel: newLabel,
          },
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #renameVersion,
            [],
            {
              #versionId: versionId,
              #newLabel: newLabel,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> clearCache() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #clearCache,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);
}

/// A class which mocks [WaveformRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWaveformRepository extends _i1.Mock
    implements _i15.WaveformRepository {
  MockWaveformRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i16.AudioWaveform>>
      getWaveformByVersionId(_i9.TrackVersionId? versionId) =>
          (super.noSuchMethod(
            Invocation.method(
              #getWaveformByVersionId,
              [versionId],
            ),
            returnValue:
                _i5.Future<_i2.Either<_i7.Failure, _i16.AudioWaveform>>.value(
                    _FakeEither_0<_i7.Failure, _i16.AudioWaveform>(
              this,
              Invocation.method(
                #getWaveformByVersionId,
                [versionId],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i7.Failure, _i16.AudioWaveform>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> deleteWaveformsForVersion(
    _i9.AudioTrackId? trackId,
    _i9.TrackVersionId? versionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWaveformsForVersion,
          [
            trackId,
            versionId,
          ],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteWaveformsForVersion,
            [
              trackId,
              versionId,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Stream<_i16.AudioWaveform> watchWaveformChanges(
          _i9.TrackVersionId? versionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchWaveformChanges,
          [versionId],
        ),
        returnValue: _i5.Stream<_i16.AudioWaveform>.empty(),
      ) as _i5.Stream<_i16.AudioWaveform>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> clearAllWaveforms() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearAllWaveforms,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #clearAllWaveforms,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> storeCanonicalWaveform({
    required _i9.AudioTrackId? trackId,
    required _i16.AudioWaveform? waveform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeCanonicalWaveform,
          [],
          {
            #trackId: trackId,
            #waveform: waveform,
          },
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #storeCanonicalWaveform,
            [],
            {
              #trackId: trackId,
              #waveform: waveform,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> storeCanonicalWaveformOnline({
    required _i9.AudioTrackId? trackId,
    required _i16.AudioWaveform? waveform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeCanonicalWaveformOnline,
          [],
          {
            #trackId: trackId,
            #waveform: waveform,
          },
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #storeCanonicalWaveformOnline,
            [],
            {
              #trackId: trackId,
              #waveform: waveform,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);
}

/// A class which mocks [AudioStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioStorageRepository extends _i1.Mock
    implements _i17.AudioStorageRepository {
  MockAudioStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i18.CacheFailure, _i19.CachedAudio>> storeAudio(
    _i9.AudioTrackId? trackId,
    _i9.TrackVersionId? versionId,
    _i14.File? audioFile, {
    _i20.DirectoryType? directoryType = _i20.DirectoryType.audioCache,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeAudio,
          [
            trackId,
            versionId,
            audioFile,
          ],
          {#directoryType: directoryType},
        ),
        returnValue:
            _i5.Future<_i2.Either<_i18.CacheFailure, _i19.CachedAudio>>.value(
                _FakeEither_0<_i18.CacheFailure, _i19.CachedAudio>(
          this,
          Invocation.method(
            #storeAudio,
            [
              trackId,
              versionId,
              audioFile,
            ],
            {#directoryType: directoryType},
          ),
        )),
      ) as _i5.Future<_i2.Either<_i18.CacheFailure, _i19.CachedAudio>>);

  @override
  _i5.Future<_i2.Either<_i18.CacheFailure, String>> getCachedAudioPath(
    _i9.AudioTrackId? trackId, {
    _i9.TrackVersionId? versionId,
    _i20.DirectoryType? directoryType = _i20.DirectoryType.audioCache,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedAudioPath,
          [trackId],
          {
            #versionId: versionId,
            #directoryType: directoryType,
          },
        ),
        returnValue: _i5.Future<_i2.Either<_i18.CacheFailure, String>>.value(
            _FakeEither_0<_i18.CacheFailure, String>(
          this,
          Invocation.method(
            #getCachedAudioPath,
            [trackId],
            {
              #versionId: versionId,
              #directoryType: directoryType,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i18.CacheFailure, String>>);

  @override
  _i5.Future<_i2.Either<_i18.CacheFailure, bool>> audioExists(
          _i9.AudioTrackId? trackId) =>
      (super.noSuchMethod(
        Invocation.method(
          #audioExists,
          [trackId],
        ),
        returnValue: _i5.Future<_i2.Either<_i18.CacheFailure, bool>>.value(
            _FakeEither_0<_i18.CacheFailure, bool>(
          this,
          Invocation.method(
            #audioExists,
            [trackId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i18.CacheFailure, bool>>);

  @override
  _i5.Future<_i2.Either<_i18.CacheFailure, bool>> audioVersionExists(
    _i9.AudioTrackId? trackId,
    _i9.TrackVersionId? versionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #audioVersionExists,
          [
            trackId,
            versionId,
          ],
        ),
        returnValue: _i5.Future<_i2.Either<_i18.CacheFailure, bool>>.value(
            _FakeEither_0<_i18.CacheFailure, bool>(
          this,
          Invocation.method(
            #audioVersionExists,
            [
              trackId,
              versionId,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i18.CacheFailure, bool>>);

  @override
  _i5.Future<_i2.Either<_i18.CacheFailure, _i19.CachedAudio?>> getCachedAudio(
          _i9.AudioTrackId? trackId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedAudio,
          [trackId],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i18.CacheFailure, _i19.CachedAudio?>>.value(
                _FakeEither_0<_i18.CacheFailure, _i19.CachedAudio?>(
          this,
          Invocation.method(
            #getCachedAudio,
            [trackId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i18.CacheFailure, _i19.CachedAudio?>>);

  @override
  _i5.Future<
      _i2.Either<_i18.CacheFailure, _i19.CachedAudio?>> getCachedAudioByVersion(
    _i9.AudioTrackId? trackId,
    _i9.TrackVersionId? versionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedAudioByVersion,
          [
            trackId,
            versionId,
          ],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i18.CacheFailure, _i19.CachedAudio?>>.value(
                _FakeEither_0<_i18.CacheFailure, _i19.CachedAudio?>(
          this,
          Invocation.method(
            #getCachedAudioByVersion,
            [
              trackId,
              versionId,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i18.CacheFailure, _i19.CachedAudio?>>);

  @override
  _i5.Future<_i2.Either<_i18.CacheFailure, _i2.Unit>> deleteAudioFile(
          _i9.AudioTrackId? trackId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAudioFile,
          [trackId],
        ),
        returnValue: _i5.Future<_i2.Either<_i18.CacheFailure, _i2.Unit>>.value(
            _FakeEither_0<_i18.CacheFailure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteAudioFile,
            [trackId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i18.CacheFailure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i18.CacheFailure, _i2.Unit>> deleteAudioVersionFile(
    _i9.AudioTrackId? trackId,
    _i9.TrackVersionId? versionId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAudioVersionFile,
          [
            trackId,
            versionId,
          ],
        ),
        returnValue: _i5.Future<_i2.Either<_i18.CacheFailure, _i2.Unit>>.value(
            _FakeEither_0<_i18.CacheFailure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteAudioVersionFile,
            [
              trackId,
              versionId,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i18.CacheFailure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i18.CacheFailure, int>> validateAndCleanCache() =>
      (super.noSuchMethod(
        Invocation.method(
          #validateAndCleanCache,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i18.CacheFailure, int>>.value(
            _FakeEither_0<_i18.CacheFailure, int>(
          this,
          Invocation.method(
            #validateAndCleanCache,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i18.CacheFailure, int>>);

  @override
  _i5.Stream<int> watchStorageUsage() => (super.noSuchMethod(
        Invocation.method(
          #watchStorageUsage,
          [],
        ),
        returnValue: _i5.Stream<int>.empty(),
      ) as _i5.Stream<int>);

  @override
  _i5.Future<_i2.Either<_i18.CacheFailure, int>> getStorageUsage() =>
      (super.noSuchMethod(
        Invocation.method(
          #getStorageUsage,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i18.CacheFailure, int>>.value(
            _FakeEither_0<_i18.CacheFailure, int>(
          this,
          Invocation.method(
            #getStorageUsage,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i18.CacheFailure, int>>);

  @override
  _i5.Future<_i2.Either<_i18.CacheFailure, int>> getAvailableStorage() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableStorage,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i18.CacheFailure, int>>.value(
            _FakeEither_0<_i18.CacheFailure, int>(
          this,
          Invocation.method(
            #getAvailableStorage,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i18.CacheFailure, int>>);

  @override
  _i5.Stream<bool> watchTrackCacheStatus(
    _i9.AudioTrackId? trackId, {
    _i9.TrackVersionId? versionId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTrackCacheStatus,
          [trackId],
          {#versionId: versionId},
        ),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  _i5.Stream<List<_i19.CachedAudio>> watchAllCachedAudios() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllCachedAudios,
          [],
        ),
        returnValue: _i5.Stream<List<_i19.CachedAudio>>.empty(),
      ) as _i5.Stream<List<_i19.CachedAudio>>);
}

/// A class which mocks [AudioCommentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioCommentRepository extends _i1.Mock
    implements _i21.AudioCommentRepository {
  MockAudioCommentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i22.AudioComment>> getCommentById(
          _i9.AudioCommentId? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommentById,
          [commentId],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i7.Failure, _i22.AudioComment>>.value(
                _FakeEither_0<_i7.Failure, _i22.AudioComment>(
          this,
          Invocation.method(
            #getCommentById,
            [commentId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i22.AudioComment>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> addComment(
          _i22.AudioComment? comment) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [comment],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #addComment,
            [comment],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Stream<_i2.Either<_i7.Failure, List<_i22.AudioComment>>>
      watchCommentsByTrack(_i9.AudioTrackId? trackId) => (super.noSuchMethod(
            Invocation.method(
              #watchCommentsByTrack,
              [trackId],
            ),
            returnValue: _i5.Stream<
                _i2.Either<_i7.Failure, List<_i22.AudioComment>>>.empty(),
          ) as _i5.Stream<_i2.Either<_i7.Failure, List<_i22.AudioComment>>>);

  @override
  _i5.Stream<_i2.Either<_i7.Failure, List<_i22.AudioComment>>>
      watchCommentsByVersion(_i9.TrackVersionId? versionId) =>
          (super.noSuchMethod(
            Invocation.method(
              #watchCommentsByVersion,
              [versionId],
            ),
            returnValue: _i5.Stream<
                _i2.Either<_i7.Failure, List<_i22.AudioComment>>>.empty(),
          ) as _i5.Stream<_i2.Either<_i7.Failure, List<_i22.AudioComment>>>);

  @override
  _i5.Stream<_i2.Either<_i7.Failure, List<_i22.AudioComment>>>
      watchRecentComments({
    required _i9.UserId? userId,
    required int? limit,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #watchRecentComments,
              [],
              {
                #userId: userId,
                #limit: limit,
              },
            ),
            returnValue: _i5.Stream<
                _i2.Either<_i7.Failure, List<_i22.AudioComment>>>.empty(),
          ) as _i5.Stream<_i2.Either<_i7.Failure, List<_i22.AudioComment>>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> deleteComment(
          _i9.AudioCommentId? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteComment,
          [commentId],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteComment,
            [commentId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> deleteAllComments() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllComments,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteAllComments,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> deleteByTrackId(
          _i9.AudioTrackId? trackId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteByTrackId,
          [trackId],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteByTrackId,
            [trackId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);

  @override
  _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>> deleteCommentsByVersion(
          _i9.TrackVersionId? versionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCommentsByVersion,
          [versionId],
        ),
        returnValue: _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i7.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteCommentsByVersion,
            [versionId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i7.Failure, _i2.Unit>>);
}
